# Generated by Django 3.1.6 on 2021-02-02 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=30, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='г', max_length=10, verbose_name='Способ исчисления')),
            ],
            options={
                'verbose_name': 'Тип исчисления',
                'verbose_name_plural': 'Типы исчисления',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заведение', max_length=25, verbose_name='Название')),
                ('adres', models.CharField(default='Ул. __, д. __', max_length=50, verbose_name='Адрес')),
                ('preview', models.ImageField(blank=True, upload_to='', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Simple', max_length=20, verbose_name='Название позиции')),
                ('cost', models.FloatField(default=23.0, verbose_name='Стоимость позиции')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя', max_length=20, verbose_name='Имя')),
                ('famName', models.CharField(default='Фамилия', max_length=20, verbose_name='Фамилия')),
                ('fathName', models.CharField(default='Отчество', max_length=20, verbose_name='Отчество')),
                ('vk', models.URLField(blank=True, default='vk.com/', verbose_name='ВК')),
                ('telegramNick', models.CharField(blank=True, default='NickName', max_length=20, verbose_name='Телеграмм')),
                ('date', models.DateField(verbose_name='Дата приёма на работу')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='Время открытия смены')),
                ('endTime', models.DateTimeField(verbose_name='Время закрытия смены')),
                ('isOpen', models.BooleanField(default=True, verbose_name='Открыта ли смена')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.place', verbose_name='Заведение')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.profile', verbose_name='Сортудник')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='StartSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количесвто')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Позиция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Начало смены',
                'verbose_name_plural': 'Начала смен',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=' ', verbose_name='Комментарий')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.position', verbose_name='Позиция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='+375331234567', max_length=13, verbose_name='Номер')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.profile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник и телефон',
                'verbose_name_plural': 'Сотрудники и телефоны',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='countType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.itemcounttype', verbose_name='Тип исчисления'),
        ),
        migrations.CreateModel(
            name='EndSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количесвто')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Позиция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Окончание смены',
                'verbose_name_plural': 'Окончания смен',
            },
        ),
        migrations.CreateModel(
            name='DeleteOnSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количесвто')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Позиция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Увоз',
                'verbose_name_plural': 'Увозы',
            },
        ),
        migrations.CreateModel(
            name='AddToSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количесвто')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Позиция')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Привоз',
                'verbose_name_plural': 'Пирвозы',
            },
        ),
    ]
