# Generated by Django 3.1.6 on 2021-02-05 02:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210203_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='endsession',
            name='comment',
            field=models.TextField(default=' ', verbose_name='Комментарий к завершению смены'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 5, 2, 4, 42, 512499, tzinfo=utc), verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 2, 4, 42, 514493, tzinfo=utc), verbose_name='Время закрытия смены'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 2, 4, 42, 514493, tzinfo=utc), verbose_name='Время открытия смены'),
        ),
        migrations.CreateModel(
            name='ImgForSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Сопроводительное изображение')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session', verbose_name='Смена')),
            ],
        ),
    ]
