# Generated by Django 3.1.6 on 2021-02-05 02:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210205_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgforsession',
            options={'verbose_name': 'Изображение для смены', 'verbose_name_plural': 'Изображения для смен'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Позиция инвентаря', 'verbose_name_plural': 'Позиции инвентаря'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция на продажу', 'verbose_name_plural': 'Позиции на продажу'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 5, 2, 18, 38, 214494, tzinfo=utc), verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 2, 18, 38, 217487, tzinfo=utc), verbose_name='Время закрытия смены'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 2, 18, 38, 217487, tzinfo=utc), verbose_name='Время открытия смены'),
        ),
    ]
